# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PriceTracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PriceTracker
  pod 'Firebase/Core'	

  target 'PriceTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PriceTrackerUITests' do
    inherit! :search_paths
    # Pods for testing

  end

end
